name: Triton
version: 3.9.0
main: com.rexcantor64.triton.plugin.SpigotPlugin
description: "A plugin that replaces any message on your server, to the receiver's\
  \ language, in real time!"
author: Rexcantor64
website: https://triton.rexcantor64.com/
depend:
 - ProtocolLib
commands:
  twin:
    description: Upload and download your config to/from the Triton Web INterface.
    usage: "/twin [code]"
permissions:
  triton.database:
    default: op
  triton.getflag:
    default: op
  triton.help:
    default: "true"
  triton.info:
    default: "true"
  triton.loglevel:
    default: op
  triton.openselector:
    default: "true"
  triton.reload:
    default: op
  triton.setlanguage:
    default: "true"
  triton.setlanguage.others:
    default: op
  triton.sign:
    default: op
  twin.download:
    default: op
  twin.upload:
    default: op
api-version: 1.13
softdepend:
 - PlaceholderAPI
